from sqlalchemy import Column, Integer, String, Enum, JSON, DateTime, func
from sqlalchemy.orm import relationship
from ..core.database import Base
import enum

class UserRole(str, enum.Enum):
    STUDENT = "STUDENT"
    TEACHER = "TEACHER"
    ADMIN = "ADMIN"  # DOS - Deputy in charge of studies
    CLASS_TEACHER = "CLASS_TEACHER"  # Teacher with class management rights

class User(Base):
    __tablename__ = "users"
    
    id = Column(Integer, primary_key=True, index=True)
    email = Column(String, unique=True, index=True, nullable=False)
    hashed_password = Column(String, nullable=False)
    full_name = Column(String, nullable=False)
    role = Column(Enum(UserRole), nullable=False)
    school_id = Column(Integer, nullable=False, index=True)
    
    # Location fields
    province = Column(String, nullable=False, index=True)
    district = Column(String, nullable=False, index=True)
    
    grade = Column(Integer, nullable=True)  # For students
    selected_trade = Column(String, nullable=True)  # For TVET students
    selected_level = Column(String, nullable=True)  # For TVET students (Level 1-6)
    attributes = Column(JSON, default={})  # clubs, teams, etc.
    locale = Column(String, default="rw")  # rw=Kinyarwanda, en, fr
    is_active = Column(Integer, default=1)
    is_class_teacher = Column(Integer, default=0)  # 1 if designated as class teacher
    managed_class_id = Column(Integer, nullable=True)  # Group ID they manage as class teacher
    generated_password = Column(String, nullable=True)  # Original password generated by DOS
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
    
    # Relationships
    messages = relationship("Message", back_populates="user", foreign_keys="Message.user_id")
    dm_requests_sent = relationship("DMRequest", foreign_keys="DMRequest.student_id", back_populates="student")
    dm_requests_received = relationship("DMRequest", foreign_keys="DMRequest.teacher_id", back_populates="teacher")
    incidents_reported = relationship("Incident", foreign_keys="Incident.reporter_id", back_populates="reporter")
